service: second-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  versionFunctions: true
  lambdaHashingVersion: 20201221
  role: arn:aws:iam::624733648801:role/Role-serverless-function
  deploymentBucket:
    name: codebuildjuver
    serverSideEncryption: AES256
  #deploymentPrefix: serverless/example
  
plugins:
  - serverless-deployment-bucket
  - serverless-plugin-canary-deployments


package:
  individually: true
  exclude:
    - "**"
    
functions:
  lambda-01:
    handler: lambda/lambda_01.greetings
    deploymentSettings:
      type: Linear10PercentEvery1Minute
      alias: Live
    package:
      include:
        - lambda/lambda_01.py
           

  
